---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: study22-acc-receiver
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: study22-acc-receiver
spec:
  ports:
    - name: http
      nodePort: 32123
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: study22-acc-receiver
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: study22-acc-receiver
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: study22-acc-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: study22-acc-receiver
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: study22-acc-receiver
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/managed-by: quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: eeengcs/study22-acc-receiver:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: study22-acc-receiver
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
