---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: study22-acc-sender
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: study22-acc-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: study22-acc-sender
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: study22-acc-sender
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: eeengcs/study22-acc-sender:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: study22-acc-sender
